config/routes.rb
Rails.application.routes.draw do

  resources :companies
  resources :initiatives
  resources :media
  resources :people
  resources :concepts
  root 'pages#index'

end

app/models/initiative.rb
class Initiative < ActiveRecord::Base
  has_many :notes
end

app/controllers/initiatives_controller.rb
class InitiativesController < ApplicationController
  before_action :set_initiative, only: [:show, :edit, :update, :destroy]

  # GET /initiatives
  # GET /initiatives.json
  def index
    @initiatives = Initiative.all
  end

  # GET /initiatives/1
  # GET /initiatives/1.json
  def show
    @note = Note.new
  end

  # GET /initiatives/new
  def new
    @initiative = Initiative.new
  end

  # GET /initiatives/1/edit
  def edit
  end

  # POST /initiatives
  # POST /initiatives.json
  def create
    @initiative = Initiative.new(initiative_params)

    respond_to do |format|
      if @initiative.save
        format.html { redirect_to @initiative, notice: 'Initiative was successfully created.' }
        format.json { render :show, status: :created, location: @initiative }
      else
        format.html { render :new }
        format.json { render json: @initiative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /initiatives/1
  # PATCH/PUT /initiatives/1.json
  def update
    respond_to do |format|
      if @initiative.update(initiative_params)
        format.html { redirect_to @initiative, notice: 'Initiative was successfully updated.' }
        format.json { render :show, status: :ok, location: @initiative }
      else
        format.html { render :edit }
        format.json { render json: @initiative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /initiatives/1
  # DELETE /initiatives/1.json
  def destroy
    @initiative.destroy
    respond_to do |format|
      format.html { redirect_to initiatives_url, notice: 'Initiative was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_initiative
    @initiative = Initiative.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def initiative_params
    params.require(:initiative).permit(:name, :organizer, :description, :location, notes_attributes: [:text, :image, :parent_id, :parent_type])
  end

  def note_params
    params.require(:note).permit(:text, :image, :parent_id, :parent_type)
  end
end

app/helpers/initiatives_helper.rb
module InitiativesHelper
end

app/views/initiatives/_form.html.erb
<%= form_for(@initiative) do |f| %>
  <% if @initiative.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@initiative.errors.count, "error") %> prohibited this initiative from being saved:</h2>

      <ul>
      <% @initiative.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :organizer %><br>
    <%= f.text_field :organizer %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/initiatives/edit.html.erb
<h1>Editing Initiative</h1>

<%= render 'form' %>

<%= link_to 'Show', @initiative %> |
<%= link_to 'Back', initiatives_path %>

app/views/initiatives/index.html.erb
<div class="container">  
  <p id="notice"><%= notice %></p>

  <h1>Listing Initiatives</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Organizer</th>
        <th>Description</th>
        <th>Location</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @initiatives.each do |initiative| %>
        <tr>
          <td><%= initiative.name %></td>
          <td><%= initiative.organizer %></td>
          <td><%= initiative.description %></td>
          <td><%= initiative.location %></td>
          <td><%= link_to 'Show', initiative %></td>
          <td><%= link_to 'Edit', edit_initiative_path(initiative) %></td>
          <td><%= link_to 'Destroy', initiative, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Initiative', new_initiative_path %>
</div>

app/views/initiatives/new.html.erb
<h1>New Initiative</h1>

<%= render 'form' %>

<%= link_to 'Back', initiatives_path %>

app/views/initiatives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @initiative.name %>
</p>

<p>
  <strong>Organizer:</strong>
  <%= @initiative.organizer %>
</p>

<p>
  <strong>Description:</strong>
  <%= @initiative.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @initiative.location %>
</p>

<%= link_to 'Edit', edit_initiative_path(@initiative) %> |
<%= link_to 'Back', initiatives_path %>