config/routes.rb
Rails.application.routes.draw do

  resources :companies
  resources :initiatives
  resources :media
  resources :people
  resources :concepts
  root 'pages#index'

end

app/views/partials/_features.html.erb
<div class="divide70"></div>
<div class="assan-features">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="center-heading">
            <h2>Latest <strong>nodes</strong></h2>
            <span class="center-line"></span>
        </div>
      </div>                   
    </div>
    <div class="row">
      <% @initiatives.each do |initiative| %>
      <div class="col-md-4 col-sm-6 margin20">
        <div class="services-box wow animated fadeIn" data-wow-duration="700ms" data-wow-delay="100ms">
          <div class="services-box-icon">
              <i class="fa fa-image"></i>
          </div><!--services icon-->
          <div class="services-box-info">
            <h4><%= initiative.name %></h4>
            <p>
                <%= initiative.description %> <%= link_to "Read more", initiative_path(initiative) %>
            </p>
          </div>
        </div><!--services box-->
      </div><!--services col-->
      <% end %>
    </div><!--services row-->
  </div>
</div><!--assan features-->

app/views/partials/_footer.html.erb
<footer id="footer">
<div class="container">

  <div class="row">
    <div class="col-md-3 col-sm-6 margin30">
      <div class="footer-col">
        <h3>About assan</h3>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer lorem quam, adipiscing condimentum tristique vel, eleifend sed turpis. Pellentesque cursus arcu id magna euismod in elementum purus molestie.
        </p>
        <ul class="list-inline social-1">
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
            <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
        </ul>
      </div>                        
    </div><!--footer col-->
    <div class="col-md-3 col-sm-6 margin30">
      <div class="footer-col">
        <h3>Contact</h3>

        <ul class="list-unstyled contact">
            <li><p><strong><i class="fa fa-map-marker"></i> Address:</strong> Minneapolis, MN</p></li> 
            <li><p><strong><i class="fa fa-envelope"></i> Mail US:</strong> <a href="#">rosanne.hoyem@gmail.com</a></p></li>
            <li> <p><strong><i class="fa fa-phone"></i> Phone:</strong> +01 555 555 5555</p></li>
            <li> <p><strong><i class="fa fa-skype"></i> Skype</strong> rosiehoyem</p></li>

        </ul>
      </div>                        
    </div><!--footer col-->
    <div class="col-md-3 col-sm-6 margin30">
      <div class="footer-col">
        <h3>Featured Work</h3>
        <ul class="list-inline f2-work">
            <li><a href="portfolio-single.html"><img src="img/img-1.jpg" class="img-responsive" alt=""></a></li>
            <li><a href="portfolio-single.html"><img src="img/img-2.jpg" class="img-responsive" alt=""></a></li>
            <li><a href="portfolio-single.html"><img src="img/img-3.jpg" class="img-responsive" alt=""></a></li>
            <li><a href="portfolio-single.html"><img src="img/img-4.jpg" class="img-responsive" alt=""></a></li>
            <li><a href="portfolio-single.html"><img src="img/img-5.jpg" class="img-responsive" alt=""></a></li>
            <li><a href="portfolio-single.html"><img src="img/img-6.jpg" class="img-responsive" alt=""></a></li>
        </ul>
      </div>                        
    </div><!--footer col-->
    <div class="col-md-3 col-sm-6 margin30">
      <div class="footer-col">
        <h3>Newsletter</h3>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer lorem quam, 
        </p>
        <form role="form" class="subscribe-form">
          <div class="input-group">
              <input type="text" class="form-control" placeholder="Enter email to subscribe">
              <span class="input-group-btn">
                  <button class="btn  btn-theme-dark btn-lg" type="submit">Ok</button>
              </span>
          </div>
        </form>
      </div>                        
    </div><!--footer col-->

  </div>
  <div class="row">
    <div class="col-md-12 text-center">
      <div class="footer-btm">
          <span>&copy;2015. Rosanne Hoyem</span>
      </div>
    </div>
  </div>
</div>
</footer><!--default footer end here-->

app/views/partials/_navigation.html.erb
<!--navigation -->
<!-- Static navbar -->
<div class="navbar navbar-default navbar-static-top yamm sticky" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><img src="img/logo.png" alt="ASSAN"></a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", root_path %></li>
        <li><%= link_to "People", people_path %></li>
        <li><%= link_to "Initiatives", initiatives_path %></li>
        <li><%= link_to "Concepts", concepts_path %></li>
        <li><%= link_to "Media", media_path %></li>
        <!--mega menu-->
        <li class="dropdown yamm-fw">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Features  <i class="fa fa-angle-down"></i></a>
        </li> <!--menu Features li end here-->
        <!--mega menu end-->    
        <li class="dropdown " data-animate="animated fadeInUp" style="z-index:500;">
          <a href="#" class="dropdown-toggle " data-toggle="dropdown"><i class="fa fa-search"></i></a>
          <ul class="dropdown-menu search-dropdown animated fadeInUp">
            <li id="dropdownForm">
              <div class="dropdown-form">
                <form class=" form-inline">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="search...">
                    <span class="input-group-btn">
                        <button class="btn btn-theme-bg" type="button">Go!</button>
                    </span>
                  </div><!--input group-->
                </form><!--form-->
              </div><!--.dropdown form-->
            </li><!--.drop form search-->
          </ul><!--.drop menu-->
        </li> <!--menu search li end here-->
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--container-->
</div><!--navbar-default-->

app/views/partials/_news.html.erb
<div class="divide70"></div>
<div class="container">
  <div class="row">
      <div class="col-md-12">
          <div class="center-heading">
              <h2><strong>latest</strong> news</h2>
              <span class="center-line"></span>
          </div>
      </div>                   
  </div>
  <div class="row">
    <div class="col-sm-4 margin30">
      <div>
        <a href="#">
            <div class="item-img-wrap">
                <img src="img/img-8.jpg" class="img-responsive" alt="workimg">
                <div class="item-img-overlay">
                    <span></span>
                </div>
            </div>                       
        </a><!--news link--> 
        <div class="news-desc">
            <span>Sports</span>
            <h4><a href="#">Lorem ipsum dollor Sit amet</a></h4>
            <span>By <a href="#">Author</a> on 24 july 2014</span> <span><a href="#">Read more...</a></span>
        </div><!--news desc-->
      </div> 
    </div><!--news col-->
    <div class="col-sm-4 margin30">
      <div>
        <a href="#">
            <div class="item-img-wrap">
                <img src="img/img-3.jpg" class="img-responsive" alt="workimg">
                <div class="item-img-overlay">
                    <span></span>
                </div>
            </div>                       
        </a><!--news link--> 
        <div class="news-desc">
            <span>Sports</span>
            <h4><a href="#">Lorem ipsum dollor Sit amet</a></h4>
            <span>By <a href="#">Author</a> on 24 july 2014</span> <span><a href="#">Read more...</a></span>
        </div><!--news desc-->
      </div> 
    </div><!--news col-->
    <div class="col-sm-4 margin30">
      <div>
        <a href="#">
            <div class="item-img-wrap">
                <img src="img/img-6.jpg" class="img-responsive" alt="workimg">
                <div class="item-img-overlay">
                    <span></span>
                </div>
            </div>                       
        </a><!--news link--> 
        <div class="news-desc">
            <span>Sports</span>
            <h4><a href="#">Lorem ipsum dollor Sit amet</a></h4>
            <span>By <a href="#">Author</a> on 24 july 2014</span> <span><a href="#">Read more...</a></span>
        </div><!--news desc-->
      </div> 
    </div><!--news col-->
  </div>
</div><!--latest news-->

app/views/partials/_portfolio.html.erb
<div class="divide80"></div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="center-heading">
        <h2>Recent <strong>Projects</strong></h2>
        <span class="center-line"></span>
      </div>
    </div>                   
  </div>
</div>
<div class="container">
  <div class="cube-masonry">

    <div id="filters-container" class="cbp-l-filters-alignCenter">
      <div data-filter="*" class="cbp-filter-item-active cbp-filter-item">
          All <div class="cbp-filter-counter"></div>
      </div>
      <div data-filter=".identity" class="cbp-filter-item">
          Identity <div class="cbp-filter-counter"></div>
      </div>
      <div data-filter=".web-design" class="cbp-filter-item">
          Web Design <div class="cbp-filter-counter"></div>
      </div>
      <div data-filter=".graphic" class="cbp-filter-item">
          Graphic <div class="cbp-filter-counter"></div>
      </div>
      <div data-filter=".graphic, .identity" class="cbp-filter-item">
          Web Design & Identity <div class="cbp-filter-counter"></div>
      </div>
    </div>

    <div id="masnory-container" class="cbp">
      <div class="cbp-item identity">
        <a class="cbp-caption cbp-lightbox" data-title="Easy Note<br>by Cosmin Capitanu" href="img/mas-1.jpg">
          <div class="cbp-caption-defaultWrap">
              <img src="img/mas-1.jpg" alt="">
          </div>
          <div class="cbp-caption-activeWrap">
            <div class="cbp-l-caption-alignCenter">
              <div class="cbp-l-caption-body">
                <div class="cbp-l-caption-title">Easy Note</div>
                <div class="cbp-l-caption-desc">by Cosmin Capitanu</div>
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="cbp-item web-design">
          <a class="cbp-caption cbp-lightbox" data-title="The Gang Blue<br>by Cosmin Capitanu"
             href="img/img-1.jpg">
              <div class="cbp-caption-defaultWrap">
                  <img src="img/img-1.jpg" alt="">
              </div>
              <div class="cbp-caption-activeWrap">
                  <div class="cbp-l-caption-alignCenter">
                      <div class="cbp-l-caption-body">
                          <div class="cbp-l-caption-title">The Gang Blue</div>
                          <div class="cbp-l-caption-desc">by Cosmin Capitanu</div>
                      </div>
                  </div>
              </div>
          </a>
      </div>
      <div class="cbp-item graphic identity">
          <a class="cbp-caption cbp-lightbox" data-title="Tiger<br>by Cosmin Capitanu"
             href="img/img-2.jpg">
            <div class="cbp-caption-defaultWrap">
                <img src="img/img-2.jpg" alt="">
            </div>
            <div class="cbp-caption-activeWrap">
              <div class="cbp-l-caption-alignCenter">
                  <div class="cbp-l-caption-body">
                      <div class="cbp-l-caption-title">Tiger</div>
                      <div class="cbp-l-caption-desc">by Cosmin Capitanu</div>
                  </div>
              </div>
            </div>
          </a>
      </div>
      <div class="cbp-item graphic">
        <a class="cbp-caption cbp-lightbox" data-title="Flat Roman Typeface Ui<br>by Cosmin Capitanu"
           href="img/mas-2.jpg">
          <div class="cbp-caption-defaultWrap">
              <img src="img/mas-2.jpg" alt="">
          </div>
          <div class="cbp-caption-activeWrap">
            <div class="cbp-l-caption-alignCenter">
              <div class="cbp-l-caption-body">
                  <div class="cbp-l-caption-title">Flat Roman Typeface Ui</div>
                  <div class="cbp-l-caption-desc">by Cosmin Capitanu</div>
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="cbp-item identity">
          <a class="cbp-caption cbp-lightbox" data-title="Seemple* Music for iPad<br>by Tiberiu Neamu"
             href="img/mas-2.jpg">
              <div class="cbp-caption-defaultWrap">
                  <img src="img/mas-1.jpg" alt="">
              </div>
              <div class="cbp-caption-activeWrap">
                  <div class="cbp-l-caption-alignCenter">
                      <div class="cbp-l-caption-body">
                          <div class="cbp-l-caption-title">Seemple* Music for iPad</div>
                          <div class="cbp-l-caption-desc">by Tiberiu Neamu</div>
                      </div>
                  </div>
              </div>
          </a>
      </div>
      <div class="cbp-item graphic">
          <a class="cbp-caption cbp-lightbox" data-title="Remind~Me More<br>by Tiberiu Neamu" href="img/img-3.jpg">
              <div class="cbp-caption-defaultWrap">
                  <img src="img/img-3.jpg" alt="">
              </div>
              <div class="cbp-caption-activeWrap">
                  <div class="cbp-l-caption-alignCenter">
                      <div class="cbp-l-caption-body">
                          <div class="cbp-l-caption-title">Remind~Me More</div>
                          <div class="cbp-l-caption-desc">by Tiberiu Neamu</div>
                      </div>
                  </div>
              </div>
          </a>
      </div>
      <div class="cbp-item web-design">
          <a class="cbp-caption cbp-lightbox" data-title="Workout Buddy<br>by Tiberiu Neamu" href="img/img-4.jpg">
              <div class="cbp-caption-defaultWrap">
                  <img src="img/img-4.jpg" alt="">
              </div>
              <div class="cbp-caption-activeWrap">
                  <div class="cbp-l-caption-alignCenter">
                      <div class="cbp-l-caption-body">
                          <div class="cbp-l-caption-title">Workout Buddy</div>
                          <div class="cbp-l-caption-desc">by Tiberiu Neamu</div>
                      </div>
                  </div>
              </div>
          </a>
      </div>
      <div class="cbp-item identity">
          <a class="cbp-caption cbp-lightbox" data-title="Volume Knob<br>by Paul Flavius Nechita" href="http://vimeo.com/156783#">
              <div class="cbp-caption-defaultWrap">
                  <img src="img/img-5.jpg" alt="">
              </div>
              <div class="cbp-caption-activeWrap">
                  <div class="cbp-l-caption-alignCenter">
                      <div class="cbp-l-caption-body">
                          <div class="cbp-l-caption-title">Volume Knob</div>
                          <div class="cbp-l-caption-desc">by Paul Flavius Nechita</div>
                      </div>
                  </div>
              </div>
          </a>
      </div>
      <div class="cbp-item identity">
          <a class="cbp-caption cbp-lightbox" data-title="Ski * Buddy<br>by Tiberiu Neamu" href="img/mas-2.jpg">
              <div class="cbp-caption-defaultWrap">
                  <img src="img/mas-1.jpg" alt="">
              </div>
              <div class="cbp-caption-activeWrap">
                  <div class="cbp-l-caption-alignCenter">
                      <div class="cbp-l-caption-body">
                          <div class="cbp-l-caption-title">Ski * Buddy</div>
                          <div class="cbp-l-caption-desc">by Tiberiu Neamu</div>
                      </div>
                  </div>
              </div>
          </a>
      </div>
      <div class="cbp-item web-design graphic">
          <a class="cbp-caption cbp-lightbox" data-title="Virtualization Icon<br>by Paul Flavius Nechita"
             href="https://www.youtube.com/watch?v=dChhzNGHgnA">
            <div class="cbp-caption-defaultWrap">
                <img src="img/img-6.jpg" alt="">
            </div>
            <div class="cbp-caption-activeWrap">
              <div class="cbp-l-caption-alignCenter">
                <div class="cbp-l-caption-body">
                    <div class="cbp-l-caption-title">Virtualization Icon</div>
                    <div class="cbp-l-caption-desc">by Paul Flavius Nechita</div>
                </div>
              </div>
            </div>
          </a>
      </div>
      <div class="cbp-item web-design graphic">
        <a class="cbp-caption cbp-lightbox" data-title="World Clock Widget<br>by Paul Flavius Nechita"
           href="img/img-7.jpg">
          <div class="cbp-caption-defaultWrap">
              <img src="img/img-7.jpg" alt="">
          </div>
          <div class="cbp-caption-activeWrap">
            <div class="cbp-l-caption-alignCenter">
              <div class="cbp-l-caption-body">
                <div class="cbp-l-caption-title">World Clock Widget</div>
                <div class="cbp-l-caption-desc">by Paul Flavius Nechita</div>
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="cbp-item web-design graphic">
        <a class="cbp-caption cbp-lightbox" data-title="Sickpuppy<br>by Cosmin Capitanu" href="img/img-8.jpg">
          <div class="cbp-caption-defaultWrap">
              <img src="img/img-8.jpg" alt="">
          </div>
          <div class="cbp-caption-activeWrap">
            <div class="cbp-l-caption-alignCenter">
              <div class="cbp-l-caption-body">
                <div class="cbp-l-caption-title">Sickpuppy</div>
                <div class="cbp-l-caption-desc">by Cosmin Capitanu</div>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>
  </div><!--.cube masonry-->
</div>
<div class="divide50"></div>
<div class="text-center">
    <a href="masonry-portfolio-4.html" class="btn btn-theme-dark btn-lg">View All Work</a>
</div>

app/views/partials/_rev_slider.html.erb
<div class="fullwidthbanner">
  <div class="tp-banner">
    <ul>
      <!-- SLIDE -->
      <li data-transition="fade" data-slotamount="5" data-masterspeed="1000" data-title="Powerful Theme">
          <!-- MAIN IMAGE -->
          <img src="img/bg-3.jpg"  alt="darkblurbg"  data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
          <div class="caption title-2 sft"
               data-x="50"
               data-y="160"
               data-speed="1000"
               data-start="1000"
               data-easing="easeOutExpo">
              Powerful multi-purpose <br>
              business template
          </div>
          <div class="caption text sfl"
               data-x="50"
               data-y="310"
               data-speed="1000"
               data-start="1800"
               data-easing="easeOutExpo">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.  <br>
              lectus. Cras porta nisl at tincidunt tincidunt.  
          </div>
          <div class="caption sfb rev-buttons tp-resizeme"
               data-x="50"
               data-y="380"
               data-speed="500"
               data-start="1800"
               data-easing="Sine.easeOut">
              <a href="#" class="btn btn-theme-bg btn-lg">Purchase Now</a>
          </div>

          <div class="caption sfb rev-buttons tp-resizeme"
               data-x="250"
               data-y="380"
               data-speed="500"
               data-start="2100"
               data-easing="Sine.easeOut">
              <a href="#" class="btn border-white btn-lg">View features</a>
          </div>

      </li>
      <!-- SLIDE -->
      <li data-transition="fade" data-slotamount="5" data-masterspeed="1000" data-title="Unique Theme">
          <!-- MAIN IMAGE -->
          <img src="img/bg-4.jpg"  alt="darkblurbg"  data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">




          <div class="caption text-center-top sft"
               data-x="center"
               data-y="210"
               data-speed="1000"
               data-start="1400"
               data-easing="easeOutExpo">
              Feel the difference
          </div>

          <div class="caption text-center-btm sfr text-center"
               data-x="center"
               data-y="265"
               data-speed="1000"
               data-start="1600"
               data-easing="easeOutExpo">

              Assan is a creative multipurpose theme, you can use it for<br>  business, corporate, portfolio, shop events, personal and more...

          </div>
          <div class="caption sfb rev-buttons tp-resizeme"
               data-x="center"
               data-y="380"
               data-speed="500"
               data-start="1800"
               data-easing="Sine.easeOut">
              <a href="#" class="btn border-white btn-lg">View features</a>
          </div>
      </li>
      <!-- SLIDE -->
      <li data-transition="fade" data-slotamount="5" data-masterspeed="1000" data-title="Multipurpose">
          <!-- MAIN IMAGE -->
          <img src="img/bg-1.jpg"  alt="darkblurbg"  data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
          <!-- LAYER NR. 1 -->
          <div class="caption left-tile-text sfr tp-resizeme"
               data-x="40"
               data-y="110" 
               data-speed="600"
               data-start="1200"
               data-end="9400"
               data-endspeed="600">Unlimited layouts
          </div>

          <!-- LAYER NR. 2 -->
          <div class="caption medium_bg_darkblue sfl medium tp-resizeme"
               data-x="40"
               data-y="170" 
               data-speed="600"
               data-start="1600"
               data-end="9400"
               data-endspeed="600"><i class="fa fa-check"></i>
          </div>

          <!-- LAYER NR. 3 -->
          <div class="caption modern_big_redbg sfb medium tp-resizeme"
               data-x="90"
               data-y="170" 
               data-speed="600"
               data-start="1600"
               data-end="9400"
               data-endspeed="600">Fully Responsive
          </div>

          <!-- LAYER NR. 4 -->
          <div class="caption medium_bg_darkblue sfl medium tp-resizeme"
               data-x="40"
               data-y="220" 
               data-speed="600"
               data-start="1800"
               data-end="9400"
               data-endspeed="600"><i class="fa fa-check"></i>
          </div>

          <!-- LAYER NR. 5 -->
          <div class="caption modern_big_redbg sfb medium tp-resizeme"
               data-x="90"
               data-y="220" 
               data-speed="600"
               data-start="1800"
               data-end="9400"
               data-endspeed="600">80+ HTML5 Valid Pages
          </div>

          <!-- LAYER NR. 6 -->
          <div class="caption medium_bg_darkblue sfl medium tp-resizeme"
               data-x="40"
               data-y="270" 
               data-speed="600"
               data-start="2000"
               data-end="9400"
               data-endspeed="600"><i class="fa fa-check"></i>
          </div>

          <!-- LAYER NR. 7 -->
          <div class="caption modern_big_redbg sfb medium tp-resizeme"
               data-x="90"
               data-y="270" 
               data-speed="600"
               data-start="2000"
               data-end="9400"
               data-endspeed="600">Slider revolution
          </div>

          <!-- LAYER NR. 8 -->
          <div class="caption medium_bg_darkblue sfl medium tp-resizeme"
               data-x="40"
               data-y="320" 
               data-speed="600"
               data-start="2200"
               data-end="9400"
               data-endspeed="600"><i class="fa fa-check"></i>
          </div>

          <!-- LAYER NR. 9 -->
          <div class="caption modern_big_redbg sfb medium tp-resizeme"
               data-x="90"
               data-y="320" 
               data-speed="600"
               data-start="2200"
               data-end="9400"
               data-endspeed="600">Clean & Commented Code
          </div>

          <!-- LAYER NR. 10 -->
          <div class="caption modern_big_redbg sfb medium tp-resizeme"
               data-x="40"
               data-y="370" 
               data-speed="600"
               data-start="2400"
               data-end="9400"
               data-endspeed="600">And Much More...
          </div>

      </li>
    </ul>
  </div>
</div><!--full width banner-->

app/views/partials/_services.html.erb
<div class="divide60"></div>
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="center-heading">
          <h2><strong>What</strong> is this site?</h2>
          <span class="center-line"></span>
          <p class="sub-text margin40">
              This is a thinking site. It captures my research, insights, and connections related to the topic of the Internet of Everything and acts as a platform to synthesize ideas. </p>
      </div>
    </div>

</div><!--center heading end-->
<div class="divide50"></div>
	<div class="row">
    <div class="col-md-3 col-sm-6 margin30">
      <div class="colored-boxed green">
          <i class="fa fa-cogs"></i>
          <h3>Resources</h3>
          <span class="center-line"></span>
          <p>
              I track thought leaders, web resources, concepts, and interesting projects from around the world here. 
          </p>
      </div>
    </div><!--colored boxed col end-->
    <div class="col-md-3 col-sm-6 margin30">
      <div class="colored-boxed dark">
          <i class="fa fa-tablet"></i>
          <h3>Idea Nodes</h3>
          <span class="center-line"></span>
          <p>
              Nodes are ways I make connections and synthesize resources and ideas. 
          </p>
      </div>
    </div><!--colored boxed col end-->
    <div class="col-md-3 col-sm-6 margin30">
      <div class="colored-boxed blue">
          <i class="fa fa-heart"></i>
          <h3>My Projects</h3>
          <span class="center-line"></span>
          <p>
              I have several on-going projects to help me further explore this topic. I'll be writing about my experiences here. 
          </p>
      </div>
    </div><!--colored boxed col end-->
    <div class="col-md-3 col-sm-6 margin30">
      <div class="colored-boxed red">
          <i class="fa fa-sliders"></i>
          <h3>Business Model Canvas</h3>
          <span class="center-line"></span>
          <p>
              I plan to use everything that I'm collecting here to create Business Model Canvas iterations. 
          </p>
      </div>
    </div><!--colored boxed col end-->
  </div>
</div><!--services container-->

app/views/partials/_team.html.erb
<div class="divide40"></div>
<div class="our-team-v-2">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="center-heading">
            <h2>Featured <strong>Thought Leaders</strong></h2>
            <span class="center-line"></span>
        </div>
      </div>                   
    </div>
    <div class="row">
      <%= @people.each do |person| %>
      <div class="col-sm-3 text-center">
        <div class="person-v2">
          <img src="<%= person.image_url %>" class="img-responsive" alt="">
          <div class="person-desc-v2">
            <h3><%= person.name %></h3>
            <em><%= person.description %> <%= link_to "Read more", person_path(person) %></em>
            <ul class="list-inline top-social">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <!-- 
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="#"><i class="fa fa-pinterest"></i></a></li>-->
            </ul>
          </div>
        </div>
      </div><!--person col end-->
      <% end %>
    </div>
  </div>
</div><!--our team v-2-->

app/views/partials/_top_nav_bar.html.erb
<div class="top-bar-dark">            
  <div class="container">
    <div class="row">
      <div class="col-sm-4 hidden-xs">
        <ul class="list-inline socials-simple">
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
            <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
            <li><a href="#"><i class="fa fa-youtube"></i></a></li>
            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
        </ul>
      </div>
      <div class="col-sm-8 text-right">
          <ul class="list-inline top-dark-right">                      
              <li class="hidden-sm hidden-xs"><i class="fa fa-envelope"></i> Support@mail.com</li>
              <li class="hidden-sm hidden-xs"><i class="fa fa-phone"></i> +01 1800 453 7678</li>
              <li><a href="shop-login.html"><i class="fa fa-lock"></i> Login</a></li>
              <li><a href="shop-register.html"><i class="fa fa-user"></i> Sign Up</a></li>
              <li><a class="topbar-icons" href="#"><span><i class="fa fa-search top-search"></i></span></a></li>
          </ul>
           <div class="search">
            <form role="form">
                <input type="text" class="form-control" autocomplete="off" placeholder="Write something and press enter">
                <span class="search-close"><i class="fa fa-times"></i></span>
            </form>
          </div>

        </div>
    </div>
  </div>
</div><!--top bar end hidden in small devices-->